In [19]:
import numpy as np

#basis
e1 = [1,-1,1,-1,1,-1]
e2 = [-1,1,-1,1,-1,1]
e3 = [1,1,1,1,1,1]
e4 = [1,1,-1,-1,1,-1]

# vectors
v1 = np.array([[1,-1,1,1,1,1]])
v2 = np.array([[-1,-1,1,1,1,1]])
v3 = np.array([[1,-1,1,-1,-1,1]])
v4 = np.array([[1,1,1,-1,-1,-1]])
v5 = np.array([[-1,-1,-1,-1,1,-1]])
v6 = np.array([[-1,-1,1,1,-1,-1]])
v7 = np.array([[1,1,1,1,1,-1]])
v8 = np.array([[1,1,-1,-1,1,-1]])
vectors = np.array([v1,v2,v3,v4,v5,v6,v7,v8])

# weight and bias
W = np.array([e1,e2,e3,e4]).T/2
b = np.array([[len(e1)/2]*4])

In [57]:
print(f"W = \n {W} \n\nbias = \n {b}")

W = 
 [[ 0.5 -0.5  0.5  0.5]
 [-0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [-0.5  0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5  0.5]
 [-0.5  0.5  0.5 -0.5]] 

bias = 
 [[3. 3. 3. 3.]]


In [31]:
from copy import deepcopy

def HammingNet(vect, weight, bias):
  return vect.dot(weight) + bias

def f_x(x):
  return np.where(x<0, 0, x)

def MaxNet(x, epsilon):
  m = len(x)
  w = np.ones((m,m)) * -epsilon
  np.fill_diagonal(w, 1)

  return f_x(w.dot(x))

def MaxNet_iteration(x, epsilon):
  x_old = deepcopy(x.flatten())
  indx = 0
  for i in range(1000):
    x_new = MaxNet(x_old, epsilon)
    x_old = x_new

    if np.count_nonzero(x_new) == 1:
      indx = int(np.flatnonzero(x_new))
      break

  return indx

def HammingNN(vect, weight, bias, epsilon):
  y_in = HammingNet(vect, weight, bias)
  ind = MaxNet_iteration(y_in, epsilon)
  return ind

In [34]:
HammingNet(v1, W, b)

array([[4., 2., 5., 2.]])

In [32]:
MaxNet_iteration(HammingNet(v1, W, b), 0.1)

2

In [35]:
HammingNN(v1, W, b, 0.1)

2

In [58]:
for cnt, vec in enumerate(vectors):
  print(f'v{cnt+1} is close to basis e{HammingNN(vec, W, b, 0.1)+1}')

v1 is close to basis e3
v2 is close to basis e3
v3 is close to basis e1
v4 is close to basis e1
v5 is close to basis e1
v6 is close to basis e2
v7 is close to basis e3
v8 is close to basis e4
